[package]
name = "ymodem-send-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kioto-serial = "0.1.0"
serialport = "4.4.0"
tokio = { version = "1.39.3", features = ["io-util"] }
